const STORAGE_KEY = "fate-rpg-site-state";

const RARITY_META = {
  Common: { key: "Common", rate: 0.54, growthMin: 2, growthMax: 4, exp: 10, className: "common" },
  Rare: { key: "Rare", rate: 0.28, growthMin: 4, growthMax: 7, exp: 18, className: "rare" },
  Epic: { key: "Epic", rate: 0.13, growthMin: 7, growthMax: 11, exp: 30, className: "epic" },
  Legendary: { key: "Legendary", rate: 0.05, growthMin: 11, growthMax: 16, exp: 50, className: "legendary" },
};

const STAT_LABELS = {
  hp: "HP",
  attack: "攻撃力",
  defense: "防御力",
  speed: "素早さ",
  luck: "運",
};

const INITIAL_PLAYER = {
  name: "星詠みの旅人",
  title: "月下の新人",
  level: 1,
  exp: 0,
  totalGrowth: 0,
  stats: {
    hp: 72,
    attack: 11,
    defense: 9,
    speed: 8,
    luck: 7,
  },
};

const ITEM_DEFS = {
  potion: {
    id: "potion",
    name: "回復薬",
    description: "HPを35回復する標準的な秘薬。",
    battleEffect: { type: "heal", amount: 35 },
    kind: "battle",
  },
  power_tonic: {
    id: "power_tonic",
    name: "強化薬",
    description: "3ターンの間、攻撃力が上がる。",
    battleEffect: { type: "buffAttack", amount: 8, turns: 3 },
    kind: "battle",
  },
  ward_talisman: {
    id: "ward_talisman",
    name: "防御札",
    description: "3ターンの間、被ダメージを抑える結界札。",
    battleEffect: { type: "buffDefense", amount: 8, turns: 3 },
    kind: "battle",
  },
  crit_charm: {
    id: "crit_charm",
    name: "クリティカルの護符",
    description: "次の攻撃が強くなり、会心率も上がる。",
    battleEffect: { type: "focusCrit", amount: 1 },
    kind: "battle",
  },
  regen_drop: {
    id: "regen_drop",
    name: "再生の雫",
    description: "即時回復しつつ、数ターン再生を得る。",
    battleEffect: { type: "regen", heal: 20, amount: 10, turns: 3 },
    kind: "battle",
  },
  card_ticket: {
    id: "card_ticket",
    name: "カードチケット",
    description: "本日の儀式とは別に、もう一度カードを引ける特別な券。",
    battleEffect: null,
    kind: "utility",
  },
};

const SHOP_ITEMS = [
  {
    id: "shop-ticket",
    name: "カードチケット",
    description: "日付制限を無視して1回追加でカードを引ける。",
    price: 1000,
    type: "item",
    target: "card_ticket",
  },
  {
    id: "shop-weapon",
    name: "武器",
    description: "常設装備。購入するたび攻撃力が+6される。",
    price: 1400,
    type: "equipment",
    target: "weapon",
    bonus: { attack: 6 },
  },
  {
    id: "shop-armor",
    name: "防具",
    description: "常設装備。購入するたび防御力が+6、HPが+12される。",
    price: 1400,
    type: "equipment",
    target: "armor",
    bonus: { defense: 6, hp: 12 },
  },
];

const WORLD_PHASES = [
  {
    phase: 1,
    title: "星屑の序章",
    description: "まだ旅は浅く、運命の門は静かに揺れている。毎日の一枚が、眠っていた素質を少しずつ目覚めさせる。",
  },
  {
    phase: 2,
    title: "月鏡の回廊",
    description: "連続訪問が続き、月の回廊が輪郭を持ちはじめる。珍しいカードと旅支度の品が落ちやすくなる。",
  },
  {
    phase: 3,
    title: "運命潮の満ちる夜",
    description: "粒子の流れが濃くなり、世界そのものが育成を歓迎する。地下深層の気配も現実味を帯びてくる。",
  },
  {
    phase: 4,
    title: "終端の観測域",
    description: "カードに宿る加護が強まり、最終試練への道が開く。十分に鍛えた旅人だけが深層へ踏み込める。",
  },
];

const BOSSES = [
  {
    id: "b1",
    floor: 1,
    name: "地下1階 星塵の門番",
    title: "星塵の門番",
    description: "地下への入口を守る観測兵。まだ浅い層だが、油断した旅人を払い落とす。",
    hp: 220, attack: 17, defense: 10, speed: 10, reward: 1000,
    imageLabel: "FLOOR 01",
  },
  {
    id: "b2",
    floor: 2,
    name: "地下2階 月蝕の槍獣",
    title: "月蝕の槍獣",
    description: "鋭い突進で防御を崩す獣影。回復と防御の判断が問われる。",
    hp: 280, attack: 20, defense: 12, speed: 11, reward: 1200,
    imageLabel: "FLOOR 02",
  },
  {
    id: "b3",
    floor: 3,
    name: "地下3階 粒光機兵ノクス",
    title: "粒光機兵ノクス",
    description: "光粒子を装甲に変える兵装体。攻撃一辺倒では削りきれない。",
    hp: 330, attack: 22, defense: 14, speed: 12, reward: 1400,
    imageLabel: "FLOOR 03",
  },
  {
    id: "b4",
    floor: 4,
    name: "地下4階 夜航の観測者",
    title: "夜航の観測者",
    description: "速さで翻弄し、先手を奪ってくる監視者。",
    hp: 380, attack: 24, defense: 15, speed: 15, reward: 1600,
    imageLabel: "FLOOR 04",
  },
  {
    id: "b5",
    floor: 5,
    name: "地下5階 宙蝕の守秘卿",
    title: "宙蝕の守秘卿",
    description: "防御と圧力を両立する中層の壁。地力が試される。",
    hp: 450, attack: 27, defense: 18, speed: 15, reward: 1800,
    imageLabel: "FLOOR 05",
  },
  {
    id: "b6",
    floor: 6,
    name: "地下6階 幻層の捕食翼",
    title: "幻層の捕食翼",
    description: "鋭い連撃と高い機動を持つ飛翔体。速度不足だと不利になる。",
    hp: 520, attack: 30, defense: 19, speed: 17, reward: 2100,
    imageLabel: "FLOOR 06",
  },
  {
    id: "b7",
    floor: 7,
    name: "地下7階 深月の断罪機",
    title: "深月の断罪機",
    description: "深層に近い加護を纏う裁定者。長期戦の備えが必要。",
    hp: 610, attack: 33, defense: 22, speed: 18, reward: 2400,
    imageLabel: "FLOOR 07",
  },
  {
    id: "b8",
    floor: 8,
    name: "地下8階 星牢の王骸",
    title: "星牢の王骸",
    description: "巨大な耐久力と重い打撃を備えた深層の王骸。",
    hp: 720, attack: 36, defense: 25, speed: 19, reward: 2800,
    imageLabel: "FLOOR 08",
  },
  {
    id: "b9",
    floor: 9,
    name: "地下9階 終夜の観測竜",
    title: "終夜の観測竜",
    description: "地下最奥の直前で待つ竜。突破には十分な育成が要る。",
    hp: 860, attack: 40, defense: 28, speed: 21, reward: 3300,
    imageLabel: "FLOOR 09",
  },
  {
    id: "b10",
    floor: 10,
    name: "地下10階 終末星喰 アストラル・デヴォア",
    title: "アストラル・デヴォア",
    description: "星と運命の残滓を喰らうラスボス。ここまで育てた全てが問われる。",
    hp: 1040, attack: 46, defense: 32, speed: 24, reward: 4500,
    imageLabel: "LAST FLOOR",
  },
];

const CARD_LIBRARY = [
  { id: "c001", name: "力の小アルカナ", rarity: "Common", description: "刃の軌跡を整え、攻撃の芯をつくる。", statEffects: { attack: 1 }, itemReward: null },
  { id: "c002", name: "守護の小アルカナ", rarity: "Common", description: "薄い盾のような加護が肩口に宿る。", statEffects: { defense: 1 }, itemReward: null },
  { id: "c003", name: "活力の小アルカナ", rarity: "Common", description: "生命の火が少しだけ強く灯る。", statEffects: { hp: 2 }, itemReward: "potion" },
  { id: "c004", name: "迅速の小アルカナ", rarity: "Common", description: "身のこなしが軽くなり、先手の気配を得る。", statEffects: { speed: 1 }, itemReward: null },
  { id: "c005", name: "幸運の小アルカナ", rarity: "Common", description: "些細な偶然が味方に傾く。", statEffects: { luck: 1 }, itemReward: null },
  { id: "c006", name: "月光の断片", rarity: "Common", description: "静かな月光が心拍を整え、防御を支える。", statEffects: { hp: 1, defense: 1 }, itemReward: null },
  { id: "c007", name: "星砂の断片", rarity: "Common", description: "星屑が刃にまとわり、命中を少し高める。", statEffects: { attack: 1, luck: 1 }, itemReward: null },
  { id: "c008", name: "風読みの札", rarity: "Common", description: "足運びと判断を同時に鋭くする。", statEffects: { speed: 1, luck: 1 }, itemReward: null },
  { id: "c009", name: "宵闇の携行灯", rarity: "Common", description: "旅路の不安を薄め、継戦力を保つ。", statEffects: { hp: 2, luck: 1 }, itemReward: null },
  { id: "c010", name: "巡礼者の印", rarity: "Common", description: "地道な鍛錬の証。全体がわずかに底上げされる。", statEffects: { hp: 1, attack: 1, defense: 1 }, itemReward: null },
  { id: "c011", name: "戦火のタロット", rarity: "Rare", description: "強い意志が攻撃の伸びを引き出す。", statEffects: { attack: 2, speed: 1 }, itemReward: "power_tonic" },
  { id: "c012", name: "月壁のタロット", rarity: "Rare", description: "防壁が二重に重なり、被弾に耐える。", statEffects: { defense: 2, hp: 1 }, itemReward: "ward_talisman" },
  { id: "c013", name: "深息のタロット", rarity: "Rare", description: "長い息が体の芯を強く保つ。", statEffects: { hp: 3, defense: 1 }, itemReward: "potion" },
  { id: "c014", name: "閃歩のタロット", rarity: "Rare", description: "間合いの出入りが洗練される。", statEffects: { speed: 2, attack: 1 }, itemReward: null },
  { id: "c015", name: "導きのタロット", rarity: "Rare", description: "運命線が濃くなり、幸運が引き寄せられる。", statEffects: { luck: 2, hp: 1 }, itemReward: "crit_charm" },
  { id: "c016", name: "銀月の槍札", rarity: "Rare", description: "先制の鋭さと攻撃の伸びを授ける。", statEffects: { attack: 2, speed: 1, luck: 1 }, itemReward: null },
  { id: "c017", name: "天蓋の守り札", rarity: "Rare", description: "視界の上に見えない庇が張られる。", statEffects: { defense: 2, luck: 1, hp: 1 }, itemReward: null },
  { id: "c018", name: "巡星の旅札", rarity: "Rare", description: "旅慣れた勘が速度と運の両方を伸ばす。", statEffects: { speed: 2, luck: 1 }, itemReward: "regen_drop" },
  { id: "c019", name: "双光の契約", rarity: "Rare", description: "攻守の均衡が大きく整う。", statEffects: { attack: 1, defense: 2, hp: 1 }, itemReward: null },
  { id: "c020", name: "運命の中書", rarity: "Rare", description: "経験を形にし、成長そのものを加速させる。", statEffects: { hp: 1, attack: 1, defense: 1, speed: 1, luck: 1 }, itemReward: null },
  { id: "c021", name: "群星継承", rarity: "Epic", description: "星々の観測記録が攻撃と運を一気に押し上げる。", statEffects: { attack: 3, luck: 2, speed: 1 }, itemReward: "crit_charm" },
  { id: "c022", name: "月界防衛線", rarity: "Epic", description: "月の輪が何重にも重なり、深い守りを築く。", statEffects: { defense: 3, hp: 3 }, itemReward: "ward_talisman" },
  { id: "c023", name: "不滅炉心", rarity: "Epic", description: "生命の炉が大きく燃え上がる。", statEffects: { hp: 5, attack: 1 }, itemReward: "regen_drop" },
  { id: "c024", name: "流星脚譜", rarity: "Epic", description: "動きそのものが一段階上の域へ入る。", statEffects: { speed: 4, attack: 1 }, itemReward: "power_tonic" },
  { id: "c025", name: "千夜の審判", rarity: "Epic", description: "運命の偏りを読み切り、複数能力を押し上げる。", statEffects: { attack: 2, defense: 2, luck: 2 }, itemReward: null },
  { id: "c026", name: "天球儀の逆光", rarity: "Epic", description: "先読みの冴えが戦い全体を有利にする。", statEffects: { speed: 2, luck: 2, defense: 1 }, itemReward: null },
  { id: "c027", name: "神託の継ぎ目", rarity: "Epic", description: "目に見えない回答が、攻守に同時に宿る。", statEffects: { hp: 2, attack: 2, defense: 2 }, itemReward: "potion" },
  { id: "c028", name: "星喚びの凱歌", rarity: "Legendary", description: "攻撃と速度が跳ね上がり、戦局を引き寄せる。", statEffects: { attack: 5, speed: 3, luck: 2 }, itemReward: "crit_charm" },
  { id: "c029", name: "月王の聖櫃", rarity: "Legendary", description: "圧倒的な加護が生命と防御を塗り替える。", statEffects: { hp: 7, defense: 5 }, itemReward: "regen_drop" },
  { id: "c030", name: "終端加護の章", rarity: "Legendary", description: "運命カードの極致。全能力を大きく引き上げる。", statEffects: { hp: 4, attack: 3, defense: 3, speed: 3, luck: 3 }, itemReward: "power_tonic" },
  { id: "c031", name: "光冠の再誕", rarity: "Legendary", description: "敗北を越える者のための再生加護。", statEffects: { hp: 6, attack: 2, defense: 2, luck: 2 }, itemReward: "potion" },
  { id: "c032", name: "運命双星", rarity: "Legendary", description: "二つの星が噛み合い、成長の質そのものを変える。", statEffects: { attack: 4, defense: 2, speed: 2, luck: 3 }, itemReward: "ward_talisman" },
];
