const FATE_ELEMENTS = [
  { id: "light", label: "光", color: "#d4b27b" },
  { id: "moon", label: "月", color: "#a6b6ff" },
  { id: "star", label: "星", color: "#9fe0ff" },
  { id: "wind", label: "風", color: "#73d7c0" },
  { id: "dream", label: "夢", color: "#c99dff" },
  { id: "silence", label: "静寂", color: "#8aa0c9" },
  { id: "spark", label: "火花", color: "#ffad6e" },
];

const TRAIT_LABELS = {
  kindness: "やさしさ",
  courage: "勇気",
  intuition: "直感",
  focus: "集中",
  harmony: "調和",
  curiosity: "冒険心",
};

const DAILY_CHOICES = [
  {
    id: "moon-window",
    title: "月明かりの窓を開ける",
    text: "静かな夜気を取り込み、気配を澄ませる。内側の声に耳を寄せる選択。",
    sigil: "月",
    element: "moon",
    effects: { intuition: 2, harmony: 1, focus: 1 },
    fortune: "見えないものを受け取る感度が上がっています。今日は急がず、気づいたことを大切に。",
  },
  {
    id: "star-map",
    title: "星図のページをめくる",
    text: "まだ行ったことのない未来を想像し、次の一歩に細い光を引く選択。",
    sigil: "星",
    element: "star",
    effects: { curiosity: 2, courage: 1, intuition: 1 },
    fortune: "遠くを見ようとする意志が、近くのチャンスまで引き寄せる一日です。",
  },
  {
    id: "lantern-step",
    title: "灯りを持って外へ出る",
    text: "小さな冒険を選び、まだ名前のない出会いに足を向ける選択。",
    sigil: "灯",
    element: "spark",
    effects: { courage: 2, curiosity: 1, kindness: 1 },
    fortune: "少し大胆な選択が、止まっていた流れを動かします。まず踏み出すことに意味があります。",
  },
  {
    id: "wind-archive",
    title: "風の書庫を整理する",
    text: "散らばった記憶と予定を整え、澄んだ流れを作るための選択。",
    sigil: "風",
    element: "wind",
    effects: { focus: 2, harmony: 1, kindness: 1 },
    fortune: "整えることがそのまま追い風になります。今日の運は、静かな丁寧さに宿ります。",
  },
  {
    id: "dream-lake",
    title: "夢の湖を覗き込む",
    text: "輪郭の曖昧な願いに形を与え、未来へそっと名前をつける選択。",
    sigil: "夢",
    element: "dream",
    effects: { intuition: 1, kindness: 1, curiosity: 2 },
    fortune: "柔らかい想像力が役に立つ日です。ふと浮かんだ案を軽く扱わないでください。",
  },
  {
    id: "silent-vow",
    title: "静寂の誓いを結ぶ",
    text: "余計なざわめきを手放し、やるべきことを深く静かに進める選択。",
    sigil: "静",
    element: "silence",
    effects: { focus: 2, harmony: 1, courage: 1 },
    fortune: "大きな音より、小さな集中が勝つ一日です。沈黙の中で輪郭が見えてきます。",
  },
];

const WORLD_STAGES = [
  {
    stage: 1,
    name: "第一夜: 星待ちの庭",
    description: "まだ静かな夜空だけが広がっています。わずかな粒子だけが、訪問者の存在を覚え始めています。",
    nextHint: "次の変化まであと1日。星が少し増えます。",
  },
  {
    stage: 2,
    name: "第二夜: 星の気配",
    description: "空に散っていた粒子が星として定着しはじめます。世界が、あなたの継続を認識しはじめた段階です。",
    nextHint: "次の変化まであと1日。月の光が濃くなります。",
  },
  {
    stage: 3,
    name: "第三夜: 月の浮上",
    description: "月と雲の演出が現れ、夜の深さに奥行きが生まれます。世界に感情が宿る入口です。",
    nextHint: "次の変化まであと1日。遠景に小さな建物が現れます。",
  },
  {
    stage: 4,
    name: "第四夜: 塔の輪郭",
    description: "小さな塔や橋の影が生まれ、ただの背景だった世界が地図のような気配を持ちはじめます。",
    nextHint: "次の変化まであと1日。案内役の存在が近づきます。",
  },
  {
    stage: 5,
    name: "第五夜: 案内役の目覚め",
    description: "世界のどこかに案内役のような存在が見え隠れし、訪問者を歓迎する気配が強くなります。",
    nextHint: "次の変化まであと1日。秘密の光が開きます。",
  },
  {
    stage: 6,
    name: "第六夜: 秘密の扉",
    description: "遠景に隠されていた扉が淡く発光し、祝福の前触れのような特別な光が現れます。",
    nextHint: "次の変化まであと1日。7日目の祝福が解放されます。",
  },
  {
    stage: 7,
    name: "第七夜: 祝福の開門",
    description: "世界は一度ひらき、祝福の粒子が空に舞います。以後は周回しながら、より深いカードが出現します。",
    nextHint: "以後は7日ごとの周回で、世界は祝福を深め続けます。",
  },
];

const CARD_LIBRARY = [
  { id: "card-001", name: "月白の灯", rarity: "common", element: "moon", description: "静かな決意が、夜をやわらかく照らす。", unlockStage: 1 },
  { id: "card-002", name: "星屑の記録帳", rarity: "common", element: "star", description: "小さな発見を忘れない者に宿る一枚。", unlockStage: 1 },
  { id: "card-003", name: "風見の標", rarity: "common", element: "wind", description: "流れの変化を読む者の手元に届く。", unlockStage: 1 },
  { id: "card-004", name: "夢うつつの栞", rarity: "common", element: "dream", description: "眠る前の願いが薄く結晶した姿。", unlockStage: 1 },
  { id: "card-005", name: "静寂の羽", rarity: "common", element: "silence", description: "音の少ない場所ほど、美しく開く運。", unlockStage: 1 },
  { id: "card-006", name: "微光の火花", rarity: "common", element: "spark", description: "小さな行動が流れを変える日を示す。", unlockStage: 1 },
  { id: "card-007", name: "黎明の粉雪", rarity: "common", element: "light", description: "朝に近い夜だけが持つ、淡い兆し。", unlockStage: 1 },
  { id: "card-008", name: "群青の月舟", rarity: "rare", element: "moon", description: "ためらいの海を渡るための静かな舟。", unlockStage: 2 },
  { id: "card-009", name: "星呼びの糸", rarity: "rare", element: "star", description: "離れた縁と出来事を結び直す糸。", unlockStage: 2 },
  { id: "card-010", name: "風灯る階段", rarity: "rare", element: "wind", description: "少し先の景色まで運ぶ見えない通路。", unlockStage: 2 },
  { id: "card-011", name: "夢紡ぎの鈴", rarity: "rare", element: "dream", description: "願いを曖昧なまま終わらせない音色。", unlockStage: 2 },
  { id: "card-012", name: "無音の観測塔", rarity: "rare", element: "silence", description: "静けさの高い場所でだけ見える未来。", unlockStage: 2 },
  { id: "card-013", name: "残光の鍵", rarity: "rare", element: "spark", description: "一瞬の決断が扉を開くときに現れる。", unlockStage: 3 },
  { id: "card-014", name: "光輪の欠片", rarity: "rare", element: "light", description: "祝福の前兆が小さく固まったもの。", unlockStage: 3 },
  { id: "card-015", name: "月影の写本", rarity: "rare", element: "moon", description: "感情の揺れを記録し、意味へ変える。", unlockStage: 3 },
  { id: "card-016", name: "流星の封書", rarity: "rare", element: "star", description: "届くべき日にだけ届く、遠い合図。", unlockStage: 3 },
  { id: "card-017", name: "風紋のしるし", rarity: "rare", element: "wind", description: "躊躇を抜ける者の足もとに残る紋。", unlockStage: 4 },
  { id: "card-018", name: "夢見の温室", rarity: "rare", element: "dream", description: "ゆっくり育つ願いを守るための部屋。", unlockStage: 4 },
  { id: "card-019", name: "静寂の園丁", rarity: "epic", element: "silence", description: "焦りを剪定し、輪郭だけを残す存在。", unlockStage: 4 },
  { id: "card-020", name: "火花の旅券", rarity: "epic", element: "spark", description: "迷いの境界を越える者に渡される証。", unlockStage: 4 },
  { id: "card-021", name: "黎明写しの鏡", rarity: "epic", element: "light", description: "まだ来ていない朝を、先に映し出す。", unlockStage: 5 },
  { id: "card-022", name: "月読の羅針", rarity: "epic", element: "moon", description: "感情の波に飲まれず進むための針。", unlockStage: 5 },
  { id: "card-023", name: "星雲の案内札", rarity: "epic", element: "star", description: "散らばる可能性の中から道筋を示す。", unlockStage: 5 },
  { id: "card-024", name: "風渡る幕屋", rarity: "epic", element: "wind", description: "滞りを吹き抜け、空気を新しく変える。", unlockStage: 5 },
  { id: "card-025", name: "夢界の果実", rarity: "legend", element: "dream", description: "長く育てた願いがようやく実った姿。", unlockStage: 6 },
  { id: "card-026", name: "静夜の門番", rarity: "legend", element: "silence", description: "秘密の扉が開く直前に現れる守り手。", unlockStage: 6 },
  { id: "card-027", name: "火花冠の継承", rarity: "legend", element: "spark", description: "挑戦を続けた者だけが受け取る冠。", unlockStage: 6 },
  { id: "card-028", name: "祝福の月環", rarity: "legend", element: "moon", description: "七夜を越えた世界の上空にだけ浮かぶ。", unlockStage: 7 },
  { id: "card-029", name: "星屑の門標", rarity: "legend", element: "star", description: "7日目の扉を記念する祝福の標識。", unlockStage: 7 },
  { id: "card-030", name: "世界樹の微睡", rarity: "mythic", element: "light", description: "周回の奥でだけ見える、世界そのものの心拍。", unlockStage: 7 },
];

const ACHIEVEMENTS = [
  { id: "first-visit", label: "はじまりの訪問者", condition: (state) => state.totalVisits >= 1 },
  { id: "three-days", label: "三夜の観測者", condition: (state) => state.visitStreak >= 3 },
  { id: "seven-days", label: "祝福の継続者", condition: (state) => state.visitStreak >= 7 },
  { id: "five-cards", label: "五枚の収集家", condition: (state) => state.cardsOwned.length >= 5 },
  { id: "fifteen-cards", label: "夜の図鑑守", condition: (state) => state.cardsOwned.length >= 15 },
  { id: "all-common", label: "基礎の星読", condition: (state) => CARD_LIBRARY.filter((card) => card.rarity === "common").every((card) => state.cardsOwned.includes(card.id)) },
];
